# Generated by Django 5.0.14 on 2026-08-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PROJECT_CREATED', 'Nouveau projet créé'), ('STEP_CHANGE', 'Nouvelle étape'), ('RISK_ADDED', 'Risque ajouté'), ('ACTION_ASSIGNED', 'Action à faire assignée'), ('MEETING_SCHEDULED', 'Réunion programmée'), ('AI_ALERT', 'Alerte IA'), ('AUDIT', 'Audit'), ('GENERIC', 'Générique')], default='GENERIC', max_length=50),
        ),
    ]
