# Generated manually to match Django's autogenerated migration format

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PROJECT_CREATED', 'Nouveau projet créé'), ('STEP_CHANGE', 'Nouvelle étape'), ('RISK_ADDED', 'Risque ajouté'), ('ACTION_ASSIGNED', 'Action à faire assignée'), ('MEETING_SCHEDULED', 'Réunion programmée'), ('TRAINING_SCHEDULED', 'Formation programmée'), ('TEAM_ADDED', 'Ajouté à une équipe projet'), ('AI_ALERT', 'Alerte IA'), ('AUDIT', 'Audit'), ('GENERIC', 'Générique')], default='GENERIC', max_length=50),
        ),
    ]
