# Generated by Django 6.0.2 on 2026-03-12 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_projet', models.CharField(editable=False, max_length=20, unique=True)),
                ('client', models.CharField(max_length=100)),
                ('type_projet', models.CharField(choices=[('forfait', 'Forfait'), ('assistance', 'Assistance Technique')], max_length=20)),
                ('departement', models.CharField(choices=[('MEDIA', 'Média & Énergie'), ('SPACE', 'Space'), ('BE', 'BE Electronique'), ('MONETIQUE', 'Monétique'), ('SI', 'SI'), ('TELECOM', 'Télécom'), ('RH', 'RH'), ('QUALITE', 'Qualité'), ('ADMIN', 'Admin')], max_length=20)),
                ('phase', models.CharField(choices=[('IDLE', 'IDLE'), ('Offre', 'Offre'), ('Kickoff', 'Kickoff'), ('Realisation', 'Réalisation'), ('Cloture', 'Clôture')], default='IDLE', max_length=20)),
                ('langages', models.JSONField(blank=True, default=list)),
                ('os_outils', models.JSONField(blank=True, default=list)),
                ('metier_generique', models.JSONField(blank=True, default=list)),
                ('metier_specifique', models.JSONField(blank=True, default=list)),
                ('devops', models.JSONField(blank=True, default=list)),
                ('management', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_crees', to=settings.AUTH_USER_MODEL)),
                ('membres', models.ManyToManyField(blank=True, related_name='projets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
