# Generated by Django 6.0.2 on 2026-05-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_audit_and_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='nom_projet',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
