# Generated by Django 6.0.2 on 2026-03-13 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('pause', 'En pause'), ('termine', 'Terminé')], default='en_cours', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rcts_crees', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rct', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Step1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cahier_charges', models.FileField(blank=True, null=True, upload_to='rct/step1/')),
                ('formulaire_frp', models.FileField(blank=True, null=True, upload_to='rct/step1/')),
                ('formulaire_interactif', models.FileField(blank=True, null=True, upload_to='rct/step1/')),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rct', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step1', to='rct.rct')),
            ],
        ),
        migrations.CreateModel(
            name='Step2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulaire_qr_final', models.FileField(blank=True, null=True, upload_to='rct/step2/')),
                ('exigences_legales', models.TextField(blank=True, default='')),
                ('offre_tech_financier', models.FileField(blank=True, null=True, upload_to='rct/step2/')),
                ('fiche_revue_offre', models.FileField(blank=True, null=True, upload_to='rct/step2/')),
                ('planning', models.FileField(blank=True, null=True, upload_to='rct/step2/')),
                ('cr_reunions', models.FileField(blank=True, null=True, upload_to='rct/step2/')),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rct', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step2', to='rct.rct')),
            ],
        ),
        migrations.CreateModel(
            name='Step3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derniere_version_offre', models.FileField(blank=True, null=True, upload_to='rct/step3/')),
                ('planning', models.FileField(blank=True, null=True, upload_to='rct/step3/')),
                ('retour_client', models.FileField(blank=True, null=True, upload_to='rct/step3/')),
                ('decision', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Offre acceptée'), ('refusee', 'Offre refusée')], default='en_attente', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rct', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step3', to='rct.rct')),
            ],
        ),
    ]
