# Generated by Django 6.0.2 on 2026-03-23 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rct', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step1',
            name='formulaire_frp',
        ),
        migrations.CreateModel(
            name='FRPForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rev1_score', models.FloatField(default=0)),
                ('rev1_conclusion', models.TextField(blank=True, default='')),
                ('rev2_score', models.FloatField(default=0)),
                ('rev2_conclusion', models.TextField(blank=True, default='')),
                ('rev3_score', models.FloatField(default=0)),
                ('rev3_conclusion', models.TextField(blank=True, default='')),
                ('rev4_score', models.FloatField(default=0)),
                ('rev4_conclusion', models.TextField(blank=True, default='')),
                ('rev5_score', models.FloatField(default=0)),
                ('rev5_conclusion', models.TextField(blank=True, default='')),
                ('rev6_score', models.FloatField(default=0)),
                ('rev6_conclusion', models.TextField(blank=True, default='')),
                ('fais1_score', models.FloatField(default=0)),
                ('fais1_commentaire', models.TextField(blank=True, default='')),
                ('fais2_score', models.FloatField(default=0)),
                ('fais2_commentaire', models.TextField(blank=True, default='')),
                ('fais3_score', models.FloatField(default=0)),
                ('fais3_commentaire', models.TextField(blank=True, default='')),
                ('fais4_score', models.FloatField(default=0)),
                ('fais4_commentaire', models.TextField(blank=True, default='')),
                ('fais5_score', models.FloatField(default=0)),
                ('fais5_commentaire', models.TextField(blank=True, default='')),
                ('fais6_score', models.FloatField(default=0)),
                ('fais6_commentaire', models.TextField(blank=True, default='')),
                ('fais7_score', models.FloatField(default=0)),
                ('fais7_commentaire', models.TextField(blank=True, default='')),
                ('decision_frp', models.CharField(blank=True, default='', max_length=20)),
                ('commentaire_final', models.TextField(blank=True, default='')),
                ('besoins_ponctuels', models.JSONField(blank=True, default=list)),
                ('rct', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frp', to='rct.rct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
