# Generated by Django 6.0.2 on 2026-04-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rct', '0004_rct_post_edit_file_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='froform',
            name='t0_possible',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
