# Generated by Django 6.0.2 on 2026-04-09 00:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_audit_and_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, editable=False, max_length=10)),
                ('process', models.CharField(choices=[('Relations Clients', 'Relations Clients'), ('Ressources', 'Ressources'), ('Planification', 'Planification'), ('Technique', 'Technique'), ('Documentation', 'Documentation'), ('Réglementaire', 'Réglementaire'), ('Sécurité', 'Sécurité'), ('Qualité', 'Qualité')], max_length=30)),
                ('activity', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('risk_type', models.CharField(choices=[('Interne', 'Interne'), ('Externe', 'Externe')], max_length=10)),
                ('origin', models.CharField(choices=[('Telnet', 'Telnet'), ('Client', 'Client')], max_length=10)),
                ('causes', models.TextField()),
                ('consequences', models.TextField()),
                ('existing_measures', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Ouvert', 'Ouvert'), ('Atténué', 'Atténué'), ('Clôturé', 'Clôturé')], default='Ouvert', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_deleted', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ResidualRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('severity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('criticality', models.IntegerField(default=0, editable=False)),
                ('level', models.CharField(default='Acceptable', editable=False, max_length=15)),
                ('mesure', models.CharField(blank=True, editable=False, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residual', to='risk_management.risk')),
            ],
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('IDLE', 'IDLE'), ('Blocked', 'Blocked'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='IDLE', max_length=12)),
                ('closure_date', models.DateField(blank=True, null=True)),
                ('registration', models.TextField(blank=True)),
                ('effectiveness_criteria', models.TextField(blank=True)),
                ('initial_value', models.CharField(blank=True, max_length=200)),
                ('final_value', models.CharField(blank=True, max_length=200)),
                ('effectiveness_percentage', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans', to=settings.AUTH_USER_MODEL)),
                ('risk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action_plan', to='risk_management.risk')),
            ],
        ),
        migrations.CreateModel(
            name='RiskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('severity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('criticality', models.IntegerField(default=0, editable=False)),
                ('level', models.CharField(default='Acceptable', editable=False, max_length=15)),
                ('mesure', models.CharField(blank=True, editable=False, max_length=100)),
                ('decision', models.CharField(blank=True, choices=[('Acceptation', 'Acceptation'), ('Réduction', 'Réduction'), ('Éradication', 'Éradication')], max_length=12)),
                ('justification', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='risk_management.risk')),
            ],
        ),
    ]
