# Generated by Django 6.0.2 on 2026-04-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='efficacite',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='activity',
            field=models.CharField(choices=[('MEDIA', 'Média & Énergie'), ('SPACE', 'Space'), ('BE', 'BE Electronique'), ('MONETIQUE', 'Monétique'), ('SI', 'SI'), ('TELECOM', 'Télécom'), ('RH', 'RH'), ('QUALITE', 'Qualité'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
