# Generated by Django 6.0.2 on 2026-05-07 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_audit_and_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=200)),
                ('type_prestation', models.CharField(default='Assistance Technique', max_length=100)),
                ('directeur_activite', models.CharField(blank=True, max_length=200)),
                ('current_step', models.IntegerField(choices=[(1, 'Lancement'), (2, 'Réalisation'), (3, 'Suivi'), (4, 'Évaluation')], default=1)),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée')], default='en_cours', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='at_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistances', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Step1_Lancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(blank=True, max_length=200)),
                ('reference_document', models.CharField(blank=True, max_length=200)),
                ('auteur', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('objectifs_principaux', models.TextField(blank=True)),
                ('contribution_client', models.TextField(blank=True)),
                ('contribution_telnet', models.TextField(blank=True)),
                ('t0_date_demarrage', models.DateField(blank=True, null=True)),
                ('duree_planifiee', models.CharField(blank=True, max_length=100)),
                ('deplacements_prevus', models.CharField(blank=True, max_length=200)),
                ('competences_requises', models.TextField(blank=True)),
                ('software_requis', models.TextField(blank=True)),
                ('hardware_requis', models.TextField(blank=True)),
                ('outils_requis', models.TextField(blank=True)),
                ('at', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step1', to='assistance_technique.assistancetechnique')),
            ],
        ),
        migrations.CreateModel(
            name='RisqueIdentifie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_risque', models.TextField()),
                ('approche_attenuation', models.TextField(blank=True)),
                ('step1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risques', to='assistance_technique.step1_lancement')),
            ],
        ),
        migrations.CreateModel(
            name='PointOuvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('responsable', models.CharField(blank=True, max_length=200)),
                ('delai', models.DateField(blank=True, null=True)),
                ('step1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_ouverts', to='assistance_technique.step1_lancement')),
            ],
        ),
        migrations.CreateModel(
            name='PlanCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reunion', models.CharField(choices=[('technique', 'Réunion technique'), ('pilotage', 'Réunion de pilotage')], max_length=20)),
                ('objectif', models.CharField(blank=True, max_length=300)),
                ('frequence', models.CharField(blank=True, max_length=100)),
                ('participants', models.CharField(blank=True, max_length=300)),
                ('element_sortie', models.CharField(blank=True, max_length=300)),
                ('step1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_communication', to='assistance_technique.step1_lancement')),
            ],
        ),
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('directeur_activite', "Directeur d'activité"), ('pm', 'Chef de projet'), ('responsable_technique', 'Responsable technique'), ('developpeur', 'Développeur'), ('valideur', 'Valideur')], max_length=30)),
                ('nom', models.CharField(max_length=200)),
                ('responsabilites', models.TextField(blank=True)),
                ('step1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='assistance_technique.step1_lancement')),
            ],
        ),
        migrations.CreateModel(
            name='FormationPlanifiee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(max_length=300)),
                ('dates', models.CharField(blank=True, max_length=200)),
                ('ressources', models.CharField(blank=True, max_length=300)),
                ('step1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='assistance_technique.step1_lancement')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partie', models.CharField(choices=[('telnet', 'Telnet'), ('client', 'Client')], max_length=10)),
                ('nom', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('step1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='assistance_technique.step1_lancement')),
            ],
        ),
        migrations.CreateModel(
            name='Step2_Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('at', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step2', to='assistance_technique.assistancetechnique')),
            ],
        ),
        migrations.CreateModel(
            name='Step3_Suivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('at', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step3', to='assistance_technique.assistancetechnique')),
            ],
        ),
        migrations.CreateModel(
            name='ReunionSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('type_reunion', models.CharField(choices=[('kick_off', 'Kick-off'), ('suivi_hebdo', 'Suivi hebdomadaire'), ('autre', 'Autre')], default='suivi_hebdo', max_length=20)),
                ('participants', models.TextField(blank=True)),
                ('actions', models.TextField(blank=True)),
                ('compte_rendu_url', models.URLField(blank=True)),
                ('step3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunions', to='assistance_technique.step3_suivi')),
            ],
        ),
        migrations.CreateModel(
            name='EquipementECME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecme_id', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=300)),
                ('type_ecme', models.CharField(blank=True, max_length=200)),
                ('fournisseur', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('disponible', 'Disponible'), ('maintenance', 'En maintenance')], default='disponible', max_length=20)),
                ('step3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='assistance_technique.step3_suivi')),
            ],
        ),
        migrations.CreateModel(
            name='ChargeRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ressource', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('semaine_1', models.FloatField(default=0)),
                ('semaine_2', models.FloatField(default=0)),
                ('semaine_3', models.FloatField(default=0)),
                ('semaine_4', models.FloatField(default=0)),
                ('step3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges_ressources', to='assistance_technique.step3_suivi')),
            ],
        ),
        migrations.CreateModel(
            name='Step4_Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(blank=True, max_length=200)),
                ('cdc_ref_commande', models.CharField(blank=True, max_length=200)),
                ('date_evaluation', models.DateField(blank=True, null=True)),
                ('client_referent', models.CharField(blank=True, max_length=200)),
                ('fonction', models.CharField(blank=True, max_length=200)),
                ('commentaire_general', models.TextField(blank=True)),
                ('capitalisation_bonne_pratique', models.TextField(blank=True)),
                ('lien_matrice_competences', models.URLField(blank=True)),
                ('nouvelles_competences', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5)),
                ('enregistrements_a_maj', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5)),
                ('formations_a_planifier', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5)),
                ('besoin_recrutement', models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], max_length=5)),
                ('at', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step4', to='assistance_technique.assistancetechnique')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantBilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(blank=True, max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('est_destinataire', models.BooleanField(default=False)),
                ('est_cc', models.BooleanField(default=False)),
                ('step4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_bilan', to='assistance_technique.step4_evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='CritereEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('organisation_processus', 'Organisation / Processus'), ('taches', 'Tâches'), ('moyens', 'Moyens'), ('comportement_competences', 'Comportement et compétences'), ('securite_information', "Sécurité de l'information")], max_length=40)),
                ('numero', models.IntegerField()),
                ('critere', models.CharField(max_length=400)),
                ('satisfaction', models.CharField(choices=[('tres_satisfait', 'Très satisfait'), ('satisfait', 'Satisfait'), ('insatisfait', 'Insatisfait'), ('tres_insatisfait', 'Très insatisfait'), ('na', 'N/A')], default='na', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('step4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteres', to='assistance_technique.step4_evaluation')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='BilanMethodesMoyens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('reponse', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non'), ('na', 'N/A'), ('-', '-')], default='-', max_length=5)),
                ('commentaire', models.TextField(blank=True)),
                ('step4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilan_methodes', to='assistance_technique.step4_evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='AppreciationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(choices=[('enquete_satisfaction', 'Enquête de satisfaction'), ('emails_satisfaction', 'Emails de satisfaction'), ('emails_nonsatisfaction', 'Emails de non-satisfaction'), ('reclamations', 'Réclamations')], max_length=30)),
                ('reponse', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non'), ('-', '-')], default='-', max_length=5)),
                ('lien_archivage', models.URLField(blank=True)),
                ('step4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appreciations', to='assistance_technique.step4_evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='ActionBilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.CharField(blank=True, max_length=50)),
                ('type_action', models.CharField(choices=[('corrective', 'Action corrective'), ('preventive', 'Action préventive'), ('amelioration', "Action d'amélioration")], max_length=20)),
                ('action', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=200)),
                ('step4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_bilan', to='assistance_technique.step4_evaluation')),
            ],
        ),
    ]
