# Generated by Django 6.0.2 on 2026-05-14 22:26

import json
from django.db import migrations, models


def convert_deplacements_to_json(apps, schema_editor):
    """Convert existing plain text deplacements_prevus to JSON list using raw SQL."""
    db = schema_editor.connection
    with db.cursor() as cursor:
        # First, set all empty/null rows to JSON empty list string
        cursor.execute(
            "UPDATE assistance_technique_step1_lancement SET deplacements_prevus = '[]' "
            "WHERE deplacements_prevus IS NULL OR deplacements_prevus = ''"
        )
        # Then fetch all non-empty rows and convert to JSON
        cursor.execute(
            "SELECT id, deplacements_prevus FROM assistance_technique_step1_lancement "
            "WHERE deplacements_prevus != '[]'"
        )
        rows = cursor.fetchall()
        for row_id, val in rows:
            try:
                parsed = json.loads(val)
                if not isinstance(parsed, list):
                    parsed = [str(parsed)]
            except (json.JSONDecodeError, TypeError):
                parsed = [v.strip() for v in str(val).split(',') if v.strip()]
            cursor.execute(
                "UPDATE assistance_technique_step1_lancement SET deplacements_prevus = %s WHERE id = %s",
                [json.dumps(parsed, ensure_ascii=False), row_id]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_technique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membreequipe',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('resp_qualite', 'Responsable Qualité'), ('chef_projet', 'Chef de Projet'), ('developpeur', 'Développeur'), ('tech_lead', 'Tech Lead'), ('ingenieur', 'Ingénieur'), ('validateur', 'Validateur'), ('charge_affaires', "Chargé d'Affaires"), ('consultant', 'Consultant'), ('stagiaire', 'Stagiaire')], max_length=30),
        ),
        # Step 1: Run data migration to convert plain text to JSON before changing field type
        migrations.RunPython(convert_deplacements_to_json, migrations.RunPython.noop),
        # Step 2: Now change the field type to JSONField
        migrations.AlterField(
            model_name='step1_lancement',
            name='deplacements_prevus',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
