# Generated by Django 6.0.2 on 2026-05-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_technique', '0002_update_deplacements_and_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='step2_realisation',
            name='livrables',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pc_audits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pc_baselines',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pc_formations_cm',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pc_gestion_branches',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pc_items_config',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pc_outils_cm',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pc_politiques',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pc_versioning_docs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pc_versioning_src',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_auteur',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_documents_ref',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_domaine',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_env_dev',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_env_test',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_formations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_incidents_secu',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_materiels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_nom_projet',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_objectif',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_outils',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_reference_doc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_version',
            field=models.CharField(blank=True, default='1.0', max_length=50),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pv_actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pv_commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pv_criteres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pv_date_revue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pv_decision',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pv_nom_projet',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pv_participants',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pv_perimetre',
            field=models.TextField(blank=True),
        ),
    ]
