# Generated by Django 6.0.2 on 2026-05-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_technique', '0003_upgrade_step2_realisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancommunication',
            name='responsable',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
