# Generated by Django 6.0.2 on 2026-05-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_technique', '0004_add_responsable_to_plan_comm'),
    ]

    operations = [
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_communication_pq',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_competences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_criteres_acceptation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_cycle_vie',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_equipe_validation',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_garantie',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_jalons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_membres_equipe_pq',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_org_client',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_phases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_planning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_presentation_projet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_reunions_pq',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_support_maintenance',
            field=models.TextField(blank=True),
        ),
    ]
