# Generated by Django 6.0.2 on 2026-05-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_technique', '0005_add_pq_full_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='step3_suivi',
            name='suivi_reunions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
