# Generated by Django 6.0.2 on 2026-05-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_technique', '0006_add_suivi_reunions_to_step3'),
    ]

    operations = [
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_cycle_vie_file',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_has_garantie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_has_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_org_chart_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pq_version_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
