# Generated by Django 6.0.2 on 2026-05-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_technique', '0007_step2_realisation_pq_cycle_vie_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step2_realisation',
            name='pv_objet_livraison',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pv_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pv_type_livraison',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
