# Generated by Django 6.0.2 on 2026-05-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_technique', '0008_add_pv_liberation_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reunionsuivi',
            name='compte_rendu_url',
        ),
        migrations.AddField(
            model_name='reunionsuivi',
            name='compte_rendu',
            field=models.FileField(blank=True, null=True, upload_to='comptes_rendus/'),
        ),
    ]
