# Generated by Django 6.0.2 on 2026-05-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_technique', '0010_step4_evaluation_bilan_activite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilanmethodesmoyens',
            name='identifiant_action',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
