# Generated by Django 6.0.2 on 2026-05-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_technique', '0011_bilanmethodesmoyens_identifiant_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilanmethodesmoyens',
            name='identifiant_action',
        ),
    ]
