# Generated by Django 6.0.2 on 2026-05-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_technique', '0012_remove_bilanmethodesmoyens_identifiant_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='step2_realisation',
            name='amp_assets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pc_branches_qa',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pc_versioning_docs_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='step2_realisation',
            name='pc_versioning_src_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
