# Generated by Django 6.0.5 on 2026-06-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_technique', '0013_step2_realisation_amp_assets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step2_realisation',
            name='amp_assets',
        ),
        migrations.RemoveField(
            model_name='step2_realisation',
            name='pc_branches_qa',
        ),
        migrations.RemoveField(
            model_name='step2_realisation',
            name='pc_versioning_docs_items',
        ),
        migrations.RemoveField(
            model_name='step2_realisation',
            name='pc_versioning_src_items',
        ),
        migrations.AddField(
            model_name='plancommunication',
            name='date_prevue',
            field=models.DateField(blank=True, null=True),
        ),
    ]
