# Generated by Django 5.0.14 on 2026-07-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_technique', '0016_reunionsuivi_add_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunionsuivi',
            name='type_reunion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
