# Generated by Django 5.0.14 on 2026-07-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_technique', '0017_alter_reunionsuivi_type_reunion'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancommunication',
            name='element_entree',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
