# Generated by Django 5.0.14 on 2026-08-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistance_technique', '0019_step4_evaluation_document_evaluation_client_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeressource',
            name='semaine_1_planifie',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='chargeressource',
            name='semaine_2_planifie',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='chargeressource',
            name='semaine_3_planifie',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='chargeressource',
            name='semaine_4_planifie',
            field=models.FloatField(default=0),
        ),
    ]
