# Generated by Django 5.0.14 on 2026-07-03 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_add_nom_projet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('vert', 'Vert — Sain'), ('orange', 'Orange — Modéré'), ('rouge', 'Rouge — Critique')], max_length=10)),
                ('features_used', models.JSONField(blank=True, default=dict)),
                ('recommendation', models.TextField(blank=True)),
                ('iso_clause', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_results', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
