# Generated by Django 5.0.14 on 2026-07-23 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('projects', '0004_add_nom_projet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('critical', 'Critique')], default='warning', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('acknowledged', 'Acquittée'), ('resolved', 'Résolue')], default='open', max_length=15)),
                ('feature_triggered', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('iso_clause', models.CharField(blank=True, max_length=150)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('ai_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='ai.airesult')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_alerts', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
