# Generated by Django 5.0.14 on 2026-09-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aialert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aialert',
            name='iso_clause',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='airesult',
            name='iso_clause',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
