# Generated by Django 6.0.2 on 2026-03-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('chef_projet', 'Chef de Projet'), ('resp_qualite', 'Responsable Qualité'), ('developpeur', 'Développeur'), ('tech_lead', 'Tech Lead'), ('ingenieur', 'Ingénieur'), ('validateur', 'Validateur'), ('charge_affaires', "Chargé d'Affaires"), ('consultant', 'Consultant'), ('stagiaire', 'Stagiaire')], default='chef_projet', max_length=20),
        ),
    ]
