# Generated manually to match Django's autogenerated migration format

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
