# Generated by Django 6.0.2 on 2026-03-30 15:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion réussie'), ('LOGIN_FAILED', 'Tentative de connexion échouée'), ('LOGOUT', 'Déconnexion'), ('ACCOUNT_LOCKED', 'Compte verrouillé'), ('PROJECT_CREATE', 'Projet créé'), ('PROJECT_UPDATE', 'Projet modifié'), ('PROJECT_DELETE', 'Projet supprimé'), ('PROJECT_VIEW', 'Projet consulté'), ('USER_CREATE', 'Utilisateur créé'), ('USER_UPDATE', 'Utilisateur modifié'), ('USER_DELETE', 'Utilisateur supprimé'), ('RCT_CREATE', 'RCT créé'), ('RCT_UPDATE', 'RCT mis à jour'), ('RCT_FINISH', 'RCT terminé'), ('ACCESS_DENIED', 'Accès refusé'), ('OTHER', 'Autre')], db_index=True, max_length=30)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('model_name', models.CharField(blank=True, max_length=50, verbose_name='Modèle')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='ID objet')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Représentation')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Anciennes valeurs')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Nouvelles valeurs')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Données supplémentaires')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx'), models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx')],
            },
        ),
    ]
