# Generated by Django 6.0.2 on 2026-04-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_audit_and_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion réussie'), ('LOGIN_FAILED', 'Tentative de connexion échouée'), ('LOGOUT', 'Déconnexion'), ('ACCOUNT_LOCKED', 'Compte verrouillé'), ('PROJECT_CREATE', 'Projet créé'), ('PROJECT_UPDATE', 'Projet modifié'), ('PROJECT_DELETE', 'Projet supprimé'), ('PROJECT_VIEW', 'Projet consulté'), ('USER_CREATE', 'Utilisateur créé'), ('USER_UPDATE', 'Utilisateur modifié'), ('USER_DELETE', 'Utilisateur supprimé'), ('RCT_CREATE', 'RCT créé'), ('RCT_UPDATE', 'RCT mis à jour'), ('RCT_FINISH', 'RCT terminé'), ('RISK_CREATE', 'Risque créé'), ('RISK_UPDATE', 'Risque modifié'), ('RISK_DELETE', 'Risque supprimé'), ('RISK_EVAL', 'Évaluation risque mise à jour'), ('ACTION_CREATE', 'Action plan créée'), ('ACTION_UPDATE', 'Action plan mise à jour'), ('ACCESS_DENIED', 'Accès refusé'), ('OTHER', 'Autre')], db_index=True, max_length=30),
        ),
    ]
